version: "3.9"
services:
  postgres:
    image: "postgres"
    environment: 
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "workers"
    ports:
      - "5432:5432"
  elasticsearch:
    image: "elasticsearch:7.14.0"
    environment:
     - "discovery.type=single-node"
    ports:
      - "9200:9200"
